name: lamp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  firebase_database: ^10.4.11
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  http: ^1.2.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
