// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1CFtn5qG6CZhWKPpUA5ps7wVp5efefw',
    appId: '1:870229200639:web:71becfb31bc63c48c686ca',
    messagingSenderId: '870229200639',
    projectId: 'lamp-8f9e9',
    authDomain: 'lamp-8f9e9.firebaseapp.com',
    databaseURL: 'https://lamp-8f9e9-default-rtdb.firebaseio.com',
    storageBucket: 'lamp-8f9e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTTVTEXovoEcomvYdLwPYCBZbQ2ptB97k',
    appId: '1:870229200639:android:64937f28baa08e69c686ca',
    messagingSenderId: '870229200639',
    projectId: 'lamp-8f9e9',
    databaseURL: 'https://lamp-8f9e9-default-rtdb.firebaseio.com',
    storageBucket: 'lamp-8f9e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYcrdptwbYTkMH6pO1Y18SAOrBs7gJoXk',
    appId: '1:870229200639:ios:dae8db50170f9a79c686ca',
    messagingSenderId: '870229200639',
    projectId: 'lamp-8f9e9',
    databaseURL: 'https://lamp-8f9e9-default-rtdb.firebaseio.com',
    storageBucket: 'lamp-8f9e9.appspot.com',
    iosBundleId: 'com.example.lamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYcrdptwbYTkMH6pO1Y18SAOrBs7gJoXk',
    appId: '1:870229200639:ios:82bbb12341a62c08c686ca',
    messagingSenderId: '870229200639',
    projectId: 'lamp-8f9e9',
    databaseURL: 'https://lamp-8f9e9-default-rtdb.firebaseio.com',
    storageBucket: 'lamp-8f9e9.appspot.com',
    iosBundleId: 'com.example.lamp.RunnerTests',
  );
}
